# Generated by Django 5.2.12 on 2026-03-13 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVCallLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tv_code', models.CharField(db_index=True, max_length=10, verbose_name='Código TV')),
                ('event_type', models.CharField(max_length=30, verbose_name='Tipo do evento')),
                ('priority', models.CharField(max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CALLED', 'Chamado'), ('CONFIRMED', 'Confirmado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=15, verbose_name='Status')),
                ('called_at', models.DateTimeField(auto_now_add=True, verbose_name='Chamado em')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tv_calls', to='events.event')),
            ],
            options={
                'verbose_name': 'Chamada TV',
                'verbose_name_plural': 'Chamadas TV',
                'ordering': ['-called_at'],
                'indexes': [models.Index(fields=['called_at', 'status'], name='tv_tvcalllo_called__ff5f5c_idx')],
            },
        ),
    ]
