# Generated by Django 5.2.12 on 2026-03-13 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('event_type', models.CharField(choices=[('AUDIENCIA', 'Audiência'), ('REUNIAO', 'Reunião'), ('PRAZO', 'Prazo'), ('CONTRATO', 'Contrato')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('start_datetime', models.DateTimeField(db_index=True, verbose_name='Início')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Local')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('color_tag', models.CharField(blank=True, max_length=7, verbose_name='Cor (hex override)')),
                ('video_link', models.URLField(blank=True, verbose_name='Link videochamada')),
                ('supplier_name', models.CharField(blank=True, max_length=255, verbose_name='Fornecedor')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('process_number', models.CharField(blank=True, max_length=50, verbose_name='Nº Processo')),
                ('tv_enabled', models.BooleanField(default=False, verbose_name='Ativar TV')),
                ('tv_priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'Alta')], default='NORMAL', max_length=10, verbose_name='Prioridade TV')),
                ('tv_code', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Código TV')),
                ('tv_call_confirmed', models.BooleanField(default=False, verbose_name='Chamada TV confirmada')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('DONE', 'Realizado'), ('CANCELLED', 'Cancelado'), ('RESCHEDULED', 'Remarcado')], db_index=True, default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='clients.client')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['start_datetime', 'event_type'], name='events_even_start_d_30ecca_idx'), models.Index(fields=['assigned_to', 'status'], name='events_even_assigne_37c10c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tv_enabled', True)), fields=('tv_code',), name='unique_tv_code_when_enabled')],
            },
        ),
    ]
