# Generated by Django 5.2.12 on 2026-03-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tv_advance_unit',
            field=models.CharField(choices=[('MINUTES', 'Minutos'), ('HOURS', 'Horas'), ('DAYS', 'Dias')], default='MINUTES', max_length=10, verbose_name='Unidade de Antecedência'),
        ),
        migrations.AddField(
            model_name='event',
            name='tv_advance_value',
            field=models.PositiveIntegerField(default=0, verbose_name='Valor de Antecedência TV'),
        ),
        migrations.AddField(
            model_name='event',
            name='tv_call_triggered',
            field=models.BooleanField(default=False, verbose_name='Chamada TV Automática Realizada'),
        ),
    ]
