# Generated by Django 5.2.12 on 2026-03-13 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFollowUp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(blank=True, choices=[('SUCCESS', 'Realizado com sucesso'), ('FAILURE', 'Não realizado'), ('POSTPONED', 'Adiado/Remarcado')], max_length=20, null=True, verbose_name='Resultado')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('timeline_log', models.JSONField(default=list, verbose_name='Linha do tempo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followups_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='events.event')),
                ('next_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_followup', to='events.event', verbose_name='Próximo evento')),
            ],
            options={
                'verbose_name': 'Follow-up',
                'verbose_name_plural': 'Follow-ups',
                'ordering': ['-created_at'],
            },
        ),
    ]
