# Generated by Django 5.2.12 on 2026-03-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfollowup',
            name='failure_reason',
            field=models.TextField(blank=True, verbose_name='Motivo da falha'),
        ),
    ]
