# Generated by Django 5.2.12 on 2026-03-13 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Código TV')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('consent_given', models.BooleanField(default=False, verbose_name='Consentimento LGPD')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Data do consentimento')),
                ('privacy_policy_version', models.CharField(blank=True, max_length=20)),
                ('is_anonymized', models.BooleanField(default=False, verbose_name='Anonimizado (LGPD)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['full_name'],
            },
        ),
    ]
