# Generated by Django 5.2.12 on 2026-03-13 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('minio_key', models.CharField(max_length=500, verbose_name='Chave MinIO')),
                ('content_type', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='Tamanho (bytes)')),
                ('is_deleted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='events.event')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'is_deleted'], name='documents_e_event_i_7c1a47_idx')],
            },
        ),
    ]
